#!/usr/bin/env php
<?php
$root = dirname(__DIR__);

if (!is_file(sprintf('%s/vendor/autoload.php', $root))) {
    $root = dirname(__DIR__, 4);
}
require sprintf('%s/vendor/autoload.php', $root);

use Symfony\Component\Console\Application;
use Microwin7\TextureProvider\Commands\UpdateIndex;

$application = new Application();

$application->add(new UpdateIndex());
$application->setDefaultCommand('update', true);
$application->run();
